services:
  - type: web
    name: laravel-backend
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon  # Choose the closest region
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value:127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: h4e-employee-data
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: